=== Dimitrije1997/Vezba3/autooglas.dtd
<!DOCTYPE AutoOglas
[
<!ELEMENT AutoOglas (Automobil)+>
<!ELEMENT Automobil (Proizvodjac, Model, Godiste, Farba, Zapremina_motora, Transmisija, Gorivo, Cena, Kontakt_prodavca)>
<!ELEMENT Proizvodjac (#PCDATA)>
<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model tip CDATA #IMPLIED>

<!ELEMENT Godiste (#PCDATA)>

<!ELEMENT Farba (Boja)>
<!ATTLIST Farba tip (akril | metalik) #REQUIRED>

<!ELEMENT Zapremina_motora (#PCDATA)>
<!ATTLIST Zapremina_motora jedinica (ccm | l) #IMPLIED>

<!ELEMENT Transmisija (Broj_brzina)>
<!ATTLIST Transmisija tip (manuelni | auto) #REQUIRED>

<!ELEMENT Gorivo (#PCDATA)>
<!ATTLIST Gorivo tng (da | ne) #IMPLIED>

<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta (din | eur) #IMPLIED>

<!ELEMENT Kontakt_prodavca (#PCDATA)>
<!ELEMENT Boja (#PCDATA)>
<!ELEMENT Broj_brzina (#PCDATA)>
]>

=== Dimitrije1997/Vezba3/autooglas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE AutoOglas SYSTEM "autooglas.dtd">

<AutoOglas>

<Automobil>
    
        <Proizvodjac>Audi</Proizvodjac>
        <Model tip="karavan">A4</Model>
        <Godiste>2009</Godiste>
        <Farba tip="metalik">
            <Boja>Bela</Boja>
        </Farba>
        <Zapremina_motora jedinica="ccm">1986</Zapremina_motora>
        <Transmisija tip="manuelni">
            <Broj_brzina>6</Broj_brzina>
        </Transmisija>
        <Gorivo tng="ne">Dizel</Gorivo>
        <Cena valuta="eur">6900</Cena>
        <Kontakt_prodavca>D&amp;B BOSS, 0611847148</Kontakt_prodavca>

</Automobil>

<Automobil>

        <Proizvodjac>Citroen</Proizvodjac>
        <Model tip="hecbek">C3</Model>
        <Godiste>2020</Godiste>
        <Farba tip="akril">
            <Boja>Belo-crvena</Boja>
        </Farba>
        <Zapremina_motora jedinica="ccm">1199</Zapremina_motora>
        <Transmisija tip="auto">
            <Broj_brzina>5</Broj_brzina>
        </Transmisija>
        <Gorivo tng="da">Benzin</Gorivo>
        <Cena valuta="eur">12100</Cena>
        <Kontakt_prodavca>Citroen Centar BOBAN, 0112928501</Kontakt_prodavca>

</Automobil>

</AutoOglas>
